POST http://localhost:5000/login
Content-Type: application/json

{
  "password": "pigeon",
  "userName": "Pigeon"
}

> {% client.global.set("authToken", response.body.token); %}

###

http://localhost:5000/get-photos
Authorization: Bearer {{authToken}}
