on:
  workflow_dispatch:
  push:
    tags:
      - 'client-[v]\d+.\d+.\d+'
      - 'client-\d+.\d+.\d+'
name: Publish client on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Setup npm
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build client
        run: npm run build:client
        env:
          REACT_APP_API_URL: https://pigeon-os-api.herokuapp.com
          REACT_APP_VERSION: $npm_package_version

      - name: Publish
        uses: jsmrcaga/action-netlify-deploy@v1.5.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: client/build
          NETLIFY_DEPLOY_TO_PROD: true
