on:
  workflow_dispatch:
  push:
    tags:
      - 'client-[v]\d+.\d+.\d+'
      - 'client-\d+.\d+.\d+'
name: Publish client on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Setup npm
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Publish
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_BASE: client
          NETLIFY_CMD: npm run build
          NETLIFY_DIR: client/build
