name: CI
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 13.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 13.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Lint
        run: npm run lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 13.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Tests
        run: npm run test
